In [13]:
# [1/22 1:25 AM] ir.pavan96 (Guest)
    
# Problem 1:
# Student:
#     - all students of class 10th
#     - for every student : roll no, name, marks of 5 subjects(evrey subject 100)
#     - Calculate the result :
#         need to stor student pass or fail in exam   
#     - topper of the calss
#     - Details of all the failed  students
class sslc:
    def __init__(self,name,rollno,marks):
        self.name= name
        self.rollno= rollno
        self.marks = marks
        
    #list of class details    
    def student_details(self):        
        return self.name,self.rollno,self.marks
   
    #list of failed students
    def failed_students(self):
        percent = ((self.marks/500)*100)
        if percent < 40:
            return percent,self.name
    
    #toper of the class
    def topper(self):
        percent = ((self.marks/500)*100)
        return percent
    
    #list of pass and failed students
    def passorfail(self):
        percent = ((self.marks/500)*100)
        if percent < 40:
            return ("Fail"),self.name
        else:
            return("pass"),self.name
     
    
student1 = sslc("pavan",10,400)
student2 =sslc("arjun",11,50)
student3 = sslc("arya",12,453)
student4 = sslc("param",14,455)
# print(student1.topper())
students = [student1,student2,student3,student4]
class_details = []
top_score = 0
failed_students_list = []
passorfail_list = []
for student in students:
    class_details.append(student.student_details()) 
print(class_details)



for student in students:
    failed_students_list.append(student.failed_students())
print(failed_students_list)



for student in students:
    if student.topper() > top_score:
        top_score = student.topper()
        name = student.name
print(top_score,name)


for student in students:
    passorfail_list.append(student.passorfail())
print(passorfail_list)
    



    
    
    
    
    
    
    
#     print(student.student_details())
#     print(student.toper())






# <https://teams.microsoft.com/l/message/19:a62aa761db9745a6b107c7dbbd78f232@thread.skype/1579636529923?tenantId=95605ae2-d8be-4f86-8098-da577d0eb45e&amp;groupId=dc579526-2ae1-4938-84e2-78db46bf4c81&amp;parentMessageId=1579636529923&amp;teamName=DS-161219 - Data Scientist Program&amp;channelName=General&amp;createdTime=1579636529923>

[('pavan', 10, 400), ('arjun', 11, 50), ('arya', 12, 453), ('param', 14, 455)]
[None, (10.0, 'arjun'), None, None]
91.0 param
[('pass', 'pavan'), ('Fail', 'arjun'), ('pass', 'arya'), ('pass', 'param')]

In [29]:
    
# Problem 1:
# Student:
#     - all students of class 10th
#     - for every student : roll no, name, marks of 5 subjects(evrey subject 100)
#     - Calculate the result :
#         need to stor student pass or fail in exam   
#     - topper of the calss
#     - Details of all the failed  students
class sslc:
    def __init__(self, id,name,marks):
        self.id =  id
        self.name = name
        self.marks = marks

    def result(self):
        if ((self.marks/500)*100) <35:
            return "Fail",self.name
    def student_results(self):
         if ((self.marks/500)*100) <35:
            return "Fail",self.name
         else:
            return "Pass", self.name
    def topper(self):
        return self.marks
        
        
student1 = sslc(1001,"pavan",430)
student2 = sslc(1002,"ammu",400)
student3 = sslc(103,"amit",480)
student4 = sslc(1004,"param",470)
student5 = sslc(1005,"ajay",40)
students = [student1, student2, student3, student4, student5]
failed_students  = []
students_result = []
for student in students:
    failed_students.append(student.result())
print(failed_students)
for student in students:
    students_result.append(student.student_results())
print(students_result)

top_score = 0

for student in students:
    if student.topper() > top_score:
        top_score = student.topper()
        name = student.name
print(top_score,name)

[None, None, None, None, ('Fail', 'ajay')]
[('Pass', 'pavan'), ('Pass', 'ammu'), ('Pass', 'amit'), ('Pass', 'param'), ('Fail', 'ajay')]
480 amit

In [1]:
import pandas as pd

In [12]:
pas = pd.read_csv('https://raw.githubusercontent.com/edyoda/Data-Scientist-program/master/Practice%20Problems/data/yellow-small%2Badult-stretch.data',names=['color','size','act','age','inflated'])

In [13]:
pas

     color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  CHILD        T
2   YELLOW  SMALL      DIP  ADULT        T
3   YELLOW  SMALL      DIP  CHILD        T
4   YELLOW  LARGE  STRETCH  ADULT        T
5   YELLOW  LARGE  STRETCH  CHILD        F
6   YELLOW  LARGE      DIP  ADULT        F
7   YELLOW  LARGE      DIP  CHILD        F
8   PURPLE  SMALL  STRETCH  ADULT        T
9   PURPLE  SMALL  STRETCH  CHILD        F
10  PURPLE  SMALL      DIP  ADULT        F
11  PURPLE  SMALL      DIP  CHILD        F
12  PURPLE  LARGE  STRETCH  ADULT        T
13  PURPLE  LARGE  STRETCH  CHILD        F
14  PURPLE  LARGE      DIP  ADULT        F
15  PURPLE  LARGE      DIP  CHILD        F